const boardMarketIndices = [
  { value: 'NIFTY 50', label: 'NIFTY 50' },
  { value: 'NIFTY NEXT 50', label: 'NIFTY Next 50' },
  { value: 'NIFTY 100', label: 'NIFTY 100' },
  { value: 'NIFTY 200', label: 'NIFTY 200' },
  { value: 'NIFTY 500', label: 'NIFTY 500' },
  {
    value: 'NIFTY500 MULTICAP 50:25:25',
    label: 'Nifty500 Multicap 50:25:25 Index',
  },
  { value: 'NIFTY MIDCAP 150', label: 'NIFTY Midcap 150' },
  { value: 'NIFTY MIDCAP 50', label: 'NIFTY Midcap 50' },
  { value: 'NIFTY MIDCAP SELECT', label: 'NIFTY Midcap Select' },
  { value: 'NIFTY FULL MIDCAP 100', label: 'NIFTY Full Midcap 100' },
  { value: 'NIFTY MIDCAP 100', label: 'NIFTY Midcap 100' },
  { value: 'NIFTY SMALLCAP 250', label: 'NIFTY Smallcap 250' },
  { value: 'NIFTY SMALLCAP 50', label: 'NIFTY Smallcap 50' },
  { value: 'NIFTY FULL SMALLCAP 100', label: 'NIFTY Full Smallcap 100' },
  { value: 'NIFTY SMALLCAP 100', label: 'NIFTY Smallcap 100' },
  { value: 'NIFTY MICROCAP 250', label: 'Nifty Microcap 250' },
  { value: 'NIFTY TOTAL MARKET', label: 'NIFTY Total Market' },
  { value: 'NIFTY LARGEMIDCAP 250', label: 'NIFTY LargeMidcap 250' },
  { value: 'NIFTY MIDSML 400', label: 'NIFTY MidSmallcap 400' },
]

const sectoralIndices = [
  { value: 'NIFTY AUTO', label: 'NIFTY Auto' },
  { value: 'NIFTY BANK', label: 'NIFTY Bank' },
  { value: 'NIFTY CONSUMER DURABLES', label: 'Nifty Consumer Durables' },
  { value: 'NIFTY FINANCIAL SERVICES', label: 'NIFTY Financial Services' },
  {
    value: 'NIFTY FINANCIAL SERVICES 25/50',
    label: 'Nifty Financial Services 25/50',
  },
  { value: 'NIFTY FMCG', label: 'NIFTY FMCG' },
  { value: 'NIFTY HEALTHCARE INDEX', label: 'Nifty Healthcare Index' },
  { value: 'NIFTY IT', label: 'NIFTY IT' },
  { value: 'NIFTY MEDIA', label: 'NIFTY Media' },
  { value: 'NIFTY METAL', label: 'NIFTY Metal' },
  { value: 'NIFTY OIL & GAS', label: 'Nifty Oil & Gas' },
  { value: 'NIFTY PHARMA', label: 'NIFTY Pharma' },
  { value: 'NIFTY PRIVATE BANK', label: 'NIFTY Private Bank' },
  { value: 'NIFTY PSU BANK', label: 'NIFTY PSU Bank' },
  { value: 'NIFTY REALTY', label: 'NIFTY Realty' },
]

const thematicIndices = [
  { value: 'NIFTY COMMODITIES', label: 'NIFTY Commodities' },
  { value: 'NIFTY CPSE', label: 'NIFTY CPSE' },
  { value: 'NIFTY ENERGY', label: 'NIFTY Energy' },
  { value: 'NIFTY100 ESG', label: 'NIFTY100 ESG' },
  { value: 'NIFTY100 ENHANCED ESG', label: 'NIFTY100 Enhanced ESG' },
  {
    value: 'NIFTY100 ESG SECTOR LEADERS',
    label: 'Nifty100 ESG Sector Leaders',
  },
  { value: 'NIFTY INDIA CONSUMPTION', label: 'NIFTY India Consumption' },
  { value: 'NIFTY INDIA DEFENCE', label: 'NIFTY India Defence' },
  { value: 'NIFTY INDIA DIGITAL', label: 'NIFTY India Digital' },
  { value: 'NIFTY INDIA MANUFACTURING', label: 'Nifty India Manufacturing' },
  { value: 'NIFTY INFRASTRUCTURE', label: 'NIFTY Infrastructure' },
  { value: 'NIFTY MIDCAP LIQUID 15', label: 'NIFTY Midcap Liquid 15' },
  { value: 'NIFTY MNC', label: 'NIFTY MNC' },
  { value: 'NIFTY PSE', label: 'NIFTY PSE' },
  { value: 'NIFTY SME EMERGE', label: 'NIFTY SME EMERGE' },
  { value: 'NIFTY SERVICES SECTOR', label: 'NIFTY Services Sector' },
  {
    value: 'NIFTY NON-CYCLICAL CONSUMER',
    label: 'NIFTY Non-cyclical Consumer',
  },
  { value: 'NIFTY MOBILITY', label: 'NIFTY Mobility' },
  { value: 'NIFTY SHARIAH 25', label: 'NIFTY Shariah 25' },
  { value: 'NIFTY100 LIQUID 15', label: 'NIFTY100 Liquid 15' },
  { value: 'NIFTY50 SHARIAH', label: 'NIFTY50 Shariah' },
  { value: 'NIFTY500 SHARIAH', label: 'NIFTY500 Shariah' },
  { value: 'NIFTY ADITYA BIRLA GROUP', label: 'NIFTY Aditya Birla Group' },
  { value: 'NIFTY MAHINDRA GROUP', label: 'NIFTY Mahindra Group' },
  { value: 'NIFTY TATA GROUP', label: 'NIFTY Tata Group' },
  { value: 'NIFTY TATA GROUP 25% CAP', label: 'NIFTY Tata Group 25% Cap' },
]

const strategyIndices = [
  { value: 'NIFTY500 VALUE 50', label: 'NIFTY500 Value 50' },
  {
    value: 'NIFTY MIDCAP150 QUALITY 50',
    label: 'NIFTY Midcap150 Quality 50',
  },
  {
    value: 'NIFTY ALPHA LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Low-Volatility 30',
  },
  {
    value: 'NIFTY QUALITY LOW-VOLATILITY 30',
    label: 'NIFTY Quality Low-Volatility 30',
  },
  {
    value: 'NIFTY ALPHA QUALITY LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Quality Low-Volatility 30',
  },
  {
    value: 'NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Quality Value Low-Volatility 30',
  },
  { value: 'NIFTY50 EQUAL WEIGHT', label: 'NIFTY50 Equal Weight' },
  { value: 'NIFTY100 EQUAL WEIGHT', label: 'NIFTY100 Equal Weight' },
  {
    value: 'NIFTY100 LOW VOLATILITY 30',
    label: 'NIFTY100 Low Volatility 30',
  },
  { value: 'NIFTY200 MOMENTUM 30', label: 'Nifty200 Momentum 30' },
  {
    value: 'NIFTY DIVIDEND OPPORTUNITIES 50',
    label: 'NIFTY Dividend Opportunities 50',
  },
  { value: 'NIFTY100 ALPHA 30', label: 'NIFTY100 Alpha 30' },
  { value: 'NIFTY ALPHA 50', label: 'NIFTY Alpha 50' },
  { value: 'NIFTY HIGH BETA 50', label: 'NIFTY High Beta 50' },
  { value: 'NIFTY LOW VOLATILITY 50', label: 'NIFTY Low Volatility 50' },
  { value: 'NIFTY200 QUALITY 30', label: 'NIFTY200 Quality 30' },
  { value: 'NIFTY100 QUALITY 30', label: 'NIFTY100 Quality 30' },
  { value: 'NIFTY50 VALUE 20', label: 'NIFTY50 Value 20' },
  { value: 'NIFTY GROWTH SECTORS 15', label: 'NIFTY Growth Sectors 15' },
]

const allIndices = [
  'NIFTY 50',
  'NIFTY NEXT 50',
  'NIFTY 100',
  'NIFTY 200',
  'NIFTY 500',
  'NIFTY500 MULTICAP 50:25:25',
  'NIFTY MIDCAP 150',
  'NIFTY MIDCAP 50',
  'NIFTY MIDCAP SELECT',
  'NIFTY FULL MIDCAP 100',
  'NIFTY MIDCAP 100',
  'NIFTY SMALLCAP 250',
  'NIFTY SMALLCAP 50',
  'NIFTY FULL SMALLCAP 100',
  'NIFTY SMALLCAP 100',
  'NIFTY MICROCAP 250',
  'NIFTY TOTAL MARKET',
  'NIFTY LARGEMIDCAP 250',
  'NIFTY MIDSML 400',
  'NIFTY AUTO',
  'NIFTY BANK',
  'NIFTY CONSUMER DURABLES',
  'NIFTY FINANCIAL SERVICES',
  'NIFTY FINANCIAL SERVICES 25/50',
  'NIFTY FMCG',
  'NIFTY HEALTHCARE INDEX',
  'NIFTY IT',
  'NIFTY MEDIA',
  'NIFTY METAL',
  'NIFTY OIL & GAS',
  'NIFTY PHARMA',
  'NIFTY PRIVATE BANK',
  'NIFTY PSU BANK',
  'NIFTY REALTY',
  'NIFTY COMMODITIES',
  'NIFTY CPSE',
  'NIFTY ENERGY',
  'NIFTY100 ESG',
  'NIFTY100 ENHANCED ESG',
  'NIFTY100 ESG SECTOR LEADERS',
  'NIFTY INDIA CONSUMPTION',
  'NIFTY INDIA DEFENCE',
  'NIFTY INDIA DIGITAL',
  'NIFTY INDIA MANUFACTURING',
  'NIFTY INFRASTRUCTURE',
  'NIFTY MIDCAP LIQUID 15',
  'NIFTY MNC',
  'NIFTY PSE',
  'NIFTY SME EMERGE',
  'NIFTY SERVICES SECTOR',
  'NIFTY NON-CYCLICAL CONSUMER',
  'NIFTY MOBILITY',
  'NIFTY SHARIAH 25',
  'NIFTY100 LIQUID 15',
  'NIFTY50 SHARIAH',
  'NIFTY500 SHARIAH',
  'NIFTY ADITYA BIRLA GROUP',
  'NIFTY MAHINDRA GROUP',
  'NIFTY TATA GROUP',
  'NIFTY TATA GROUP 25% CAP',
  'NIFTY500 VALUE 50',
  'NIFTY MIDCAP150 QUALITY 50',
  'NIFTY ALPHA LOW-VOLATILITY 30',
  'NIFTY QUALITY LOW-VOLATILITY 30',
  'NIFTY ALPHA QUALITY LOW-VOLATILITY 30',
  'NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30',
  'NIFTY50 EQUAL WEIGHT',
  'NIFTY100 EQUAL WEIGHT',
  'NIFTY100 LOW VOLATILITY 30',
  'NIFTY200 MOMENTUM 30',
  'NIFTY DIVIDEND OPPORTUNITIES 50',
  'NIFTY100 ALPHA 30',
  'NIFTY ALPHA 50',
  'NIFTY HIGH BETA 50',
  'NIFTY LOW VOLATILITY 50',
  'NIFTY200 QUALITY 30',
  'NIFTY100 QUALITY 30',
  'NIFTY50 VALUE 20',
  'NIFTY GROWTH SECTORS 15',
] as const

export type IndexName = typeof allIndices[number]
