const boardMarketIndices = [
  { value: 'NIFTY 50', label: 'NIFTY 50' },
  { value: 'NIFTY NEXT 50', label: 'NIFTY Next 50' },
  { value: 'NIFTY 100', label: 'NIFTY 100' },
  { value: 'NIFTY 200', label: 'NIFTY 200' },
  { value: 'NIFTY 500', label: 'NIFTY 500' },
  {
    value: 'NIFTY500 MULTICAP 50:25:25',
    label: 'Nifty500 Multicap 50:25:25 Index',
  },
  { value: 'NIFTY MIDCAP 150', label: 'NIFTY Midcap 150' },
  { value: 'NIFTY MIDCAP 50', label: 'NIFTY Midcap 50' },
  { value: 'NIFTY MIDCAP SELECT', label: 'NIFTY Midcap Select' },
  { value: 'NIFTY FULL MIDCAP 100', label: 'NIFTY Full Midcap 100' },
  { value: 'NIFTY MIDCAP 100', label: 'NIFTY Midcap 100' },
  { value: 'NIFTY SMALLCAP 250', label: 'NIFTY Smallcap 250' },
  { value: 'NIFTY SMALLCAP 50', label: 'NIFTY Smallcap 50' },
  { value: 'NIFTY FULL SMALLCAP 100', label: 'NIFTY Full Smallcap 100' },
  { value: 'NIFTY SMALLCAP 100', label: 'NIFTY Smallcap 100' },
  { value: 'NIFTY MICROCAP 250', label: 'Nifty Microcap 250' },
  { value: 'NIFTY TOTAL MARKET', label: 'NIFTY Total Market' },
  { value: 'NIFTY LARGEMIDCAP 250', label: 'NIFTY LargeMidcap 250' },
  { value: 'NIFTY MIDSML 400', label: 'NIFTY MidSmallcap 400' },
]

const sectoralIndices = [
  { value: 'NIFTY AUTO', label: 'NIFTY Auto' },
  { value: 'NIFTY BANK', label: 'NIFTY Bank' },
  { value: 'NIFTY CONSUMER DURABLES', label: 'Nifty Consumer Durables' },
  { value: 'NIFTY FINANCIAL SERVICES', label: 'NIFTY Financial Services' },
  {
    value: 'NIFTY FINANCIAL SERVICES 25/50',
    label: 'Nifty Financial Services 25/50',
  },
  { value: 'NIFTY FMCG', label: 'NIFTY FMCG' },
  { value: 'NIFTY HEALTHCARE INDEX', label: 'Nifty Healthcare Index' },
  { value: 'NIFTY IT', label: 'NIFTY IT' },
  { value: 'NIFTY MEDIA', label: 'NIFTY Media' },
  { value: 'NIFTY METAL', label: 'NIFTY Metal' },
  { value: 'NIFTY OIL & GAS', label: 'Nifty Oil & Gas' },
  { value: 'NIFTY PHARMA', label: 'NIFTY Pharma' },
  { value: 'NIFTY PRIVATE BANK', label: 'NIFTY Private Bank' },
  { value: 'NIFTY PSU BANK', label: 'NIFTY PSU Bank' },
  { value: 'NIFTY REALTY', label: 'NIFTY Realty' },
]

const thematicIndices = [
  { value: 'NIFTY COMMODITIES', label: 'NIFTY Commodities' },
  { value: 'NIFTY CPSE', label: 'NIFTY CPSE' },
  { value: 'NIFTY ENERGY', label: 'NIFTY Energy' },
  { value: 'NIFTY100 ESG', label: 'NIFTY100 ESG' },
  { value: 'NIFTY100 ENHANCED ESG', label: 'NIFTY100 Enhanced ESG' },
  {
    value: 'NIFTY100 ESG SECTOR LEADERS',
    label: 'Nifty100 ESG Sector Leaders',
  },
  { value: 'NIFTY INDIA CONSUMPTION', label: 'NIFTY India Consumption' },
  { value: 'NIFTY INDIA DEFENCE', label: 'NIFTY India Defence' },
  { value: 'NIFTY INDIA DIGITAL', label: 'NIFTY India Digital' },
  { value: 'NIFTY INDIA MANUFACTURING', label: 'Nifty India Manufacturing' },
  { value: 'NIFTY INFRASTRUCTURE', label: 'NIFTY Infrastructure' },
  { value: 'NIFTY MIDCAP LIQUID 15', label: 'NIFTY Midcap Liquid 15' },
  { value: 'NIFTY MNC', label: 'NIFTY MNC' },
  { value: 'NIFTY PSE', label: 'NIFTY PSE' },
  { value: 'NIFTY SME EMERGE', label: 'NIFTY SME EMERGE' },
  { value: 'NIFTY SERVICES SECTOR', label: 'NIFTY Services Sector' },
  {
    value: 'NIFTY NON-CYCLICAL CONSUMER',
    label: 'NIFTY Non-cyclical Consumer',
  },
  { value: 'NIFTY MOBILITY', label: 'NIFTY Mobility' },
  { value: 'NIFTY SHARIAH 25', label: 'NIFTY Shariah 25' },
  { value: 'NIFTY100 LIQUID 15', label: 'NIFTY100 Liquid 15' },
  { value: 'NIFTY50 SHARIAH', label: 'NIFTY50 Shariah' },
  { value: 'NIFTY500 SHARIAH', label: 'NIFTY500 Shariah' },
  { value: 'NIFTY ADITYA BIRLA GROUP', label: 'NIFTY Aditya Birla Group' },
  { value: 'NIFTY MAHINDRA GROUP', label: 'NIFTY Mahindra Group' },
  { value: 'NIFTY TATA GROUP', label: 'NIFTY Tata Group' },
  { value: 'NIFTY TATA GROUP 25% CAP', label: 'NIFTY Tata Group 25% Cap' },
]

const strategyIndices = [
  { value: 'NIFTY500 VALUE 50', label: 'NIFTY500 Value 50' },
  {
    value: 'NIFTY MIDCAP150 QUALITY 50',
    label: 'NIFTY Midcap150 Quality 50',
  },
  {
    value: 'NIFTY ALPHA LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Low-Volatility 30',
  },
  {
    value: 'NIFTY QUALITY LOW-VOLATILITY 30',
    label: 'NIFTY Quality Low-Volatility 30',
  },
  {
    value: 'NIFTY ALPHA QUALITY LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Quality Low-Volatility 30',
  },
  {
    value: 'NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30',
    label: 'NIFTY Alpha Quality Value Low-Volatility 30',
  },
  { value: 'NIFTY50 EQUAL WEIGHT', label: 'NIFTY50 Equal Weight' },
  { value: 'NIFTY100 EQUAL WEIGHT', label: 'NIFTY100 Equal Weight' },
  {
    value: 'NIFTY100 LOW VOLATILITY 30',
    label: 'NIFTY100 Low Volatility 30',
  },
  { value: 'NIFTY200 MOMENTUM 30', label: 'Nifty200 Momentum 30' },
  {
    value: 'NIFTY DIVIDEND OPPORTUNITIES 50',
    label: 'NIFTY Dividend Opportunities 50',
  },
  { value: 'NIFTY100 ALPHA 30', label: 'NIFTY100 Alpha 30' },
  { value: 'NIFTY ALPHA 50', label: 'NIFTY Alpha 50' },
  { value: 'NIFTY HIGH BETA 50', label: 'NIFTY High Beta 50' },
  { value: 'NIFTY LOW VOLATILITY 50', label: 'NIFTY Low Volatility 50' },
  { value: 'NIFTY200 QUALITY 30', label: 'NIFTY200 Quality 30' },
  { value: 'NIFTY100 QUALITY 30', label: 'NIFTY100 Quality 30' },
  { value: 'NIFTY50 VALUE 20', label: 'NIFTY50 Value 20' },
  { value: 'NIFTY GROWTH SECTORS 15', label: 'NIFTY Growth Sectors 15' },
]
